// TODO : 
"addi %[CPI4_cnt], %[CPI4_cnt], 1\n\t"
"addi t1, zero, 8\n\t"
"addi %[CPI3_cnt], %[CPI3_cnt], 1\n\t"
"vsetvli t0, t1, e16, ta, ma\n\t" 
"addi %[CPI5_cnt], %[CPI5_cnt], 1\n\t"
"vle64.v v0, (%[p_x])\n\t" 
"addi %[CPI4_cnt], %[CPI4_cnt], 1\n\t"
"add t5, %[p_x], 18\n\t"
"addi %[CPI4_cnt], %[CPI4_cnt], 1\n\t"
"addi t6, zero, -1\n\t"
"1:\n\t"
"addi %[CPI5_cnt], %[CPI5_cnt], 1\n\t"
"lh t4, (%[p_x])\n\t"
"addi %[CPI4_cnt], %[CPI4_cnt], 1\n\t"
"addi %[p_x], %[p_x], 2\n\t"
"addi %[CPI3_cnt], %[CPI3_cnt], 1\n\t"
"beq %[p_x], t5, 2f\n\t"
"addi %[CPI4_cnt], %[CPI4_cnt], 1\n\t"
"sub t3, %[target], t4\n\t"
"addi %[CPI3_cnt], %[CPI3_cnt], 1\n\t"
"vmseq.vx v1, v0, t3\n\t"
"addi %[CPI3_cnt], %[CPI3_cnt], 1\n\t"
"vfirst.m t2, v1\n\t"
"addi %[CPI3_cnt], %[CPI3_cnt], 1\n\t"
"beq t2, t6, 1b\n\t"
"addi %[CPI4_cnt], %[CPI4_cnt], 1\n\t"
"addi %[flag], %[flag], 1\n\t"
"2:\n\t"
